### ISSUE TITLE
413 Request Entity Too Large error in gitlab runner while running the deployment

### ISSUE THREAD

**Issue by taragurung** [UiPath-Services/UiPath-DevOps-Scripts#12]
The deployment has started to fail now with following error message
`uipcli: Data collection is enabled. For more information, please visit https://docs.uipath.com/test-suite/automation-suite/2023.4/user-guide/uipath-command-line-interface
FeedId for FolderId 829345: .
5/6/2024 10:29:22 AM	Unable to deploy project. Exit code 1
System.InvalidOperationException: Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'RequestEntityTooLarge'
   at UiPath.Web.Client20_4.Processes.UploadPackageWithHttpMessagesAsync(Stream file, Nullable`1 feedId, Stream file1, Stream file2, Stream file3, Stream file4, Stream file5, Stream file6, Stream file7, Stream file8, Stream file9, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at UiPath.Orchestrator.Client.Util.ExceptionsHandler.RunWithFriendlyExceptionMessages[T](Func`1 func)
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx</center>
</body>
</html>
   at UiPath.Orchestrator.Client.Util.ExceptionsHandler.RunWithFriendlyExceptionMessages[T](Func`1 func)
   at UiPath.Orchestrator.Client.Endpoints.Processes.UploadPackagesAsync(List`1 files, Nullable`1 feedId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at UiPath.CommandLine.Services.Impl.DeployService.UploadPackage(String correlationId, IOrchestratorClient client, String packagePath, PackageType packageType, String orchestratorUrl, String orchestratorTenant)
   at UiPath.CommandLine.Services.Impl.DeployService.<>c__DisplayClass5_0.<<UploadPackageAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Extensions.EnumerableExtensions.<>c__DisplayClass0_0`2.<<SelectParallel>b__2>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Extensions.EnumerableExtensions.SelectParallel[TIn,TOut](IEnumerable`1 inputList, Func`2 function, Int32 numberOfObjectsInParallel, CancellationToken token)
   at UiPath.CommandLine.Services.Impl.DeployService.Run(DeployOptions options)
   at UiPath.CommandLine.Services.Impl.OptionsParser.<>c__DisplayClass11_0.<<WithTelemetry>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Services.Impl.OptionsParser.<>c__DisplayClass10_0.<<WithBusinessTraces>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Services.Impl.OptionsParser.<>c__DisplayClass9_0.<<WithTraceLogging>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at UiPath.CommandLine.Services.Impl.OptionsParser.RunOptions(String[] args, Func`3 notParsedFunc)`

**Comment by SE-Abdullah** [comment]
Hi @taragurung, thank you for reporting this.
Can you tell me the size of the NuGet package you are trying to deploy to orchestrator?
Are you facing this issue with one specific NuGet package or all packages even small ones? 
Are you using Cloud or on-prem?

**Comment by taragurung** [comment]
The package size is more then 300MB now. and should be the reason for not working
And we are using Cloud so, is it possible to increase it for Cloud?

**Comment by SE-Abdullah** [comment]
I'm not sure what the limit is but for sure 300mb for an RPA nuget package is very large and unusual. Try to reduce the file size by removing unnecessary files including from the screenshot folder in the project.
This error is returned from the CLI and not from the PowerShell scripts in this solutions.
